# Generated by Django 4.1.7 on 2023-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billType',
            field=models.CharField(choices=[('rent', 'Rent or mortgage payment'), ('electricity', 'Electricity bill'), ('gas', 'Gas bill'), ('water', 'Water bill'), ('internet', 'Internet bill'), ('cable', 'Cable or satellite TV bill'), ('phone', 'Phone bill'), ('car_payment', 'Car payment (if applicable)'), ('car_insurance', 'Car insurance'), ('health_insurance', 'Health insurance'), ('life_insurance', 'Life insurance'), ('home_insurance', 'Homeowners or renters insurance'), ('property_tax', 'Property tax (if you own a home)'), ('credit_card', 'Credit card bills'), ('student_loan', 'Student loan payments (if applicable)'), ('childcare', 'Childcare expenses'), ('groceries', 'Groceries'), ('clothing', 'Clothing expenses'), ('entertainment', 'Entertainment expenses'), ('medical', 'Medical expenses (co-pays, prescriptions, etc.)'), ('other', 'Other')], max_length=25),
        ),
    ]
