# Generated by Django 4.1.7 on 2023-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bill_billdescription_alter_bill_billtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
