# Generated by Django 4.1.7 on 2023-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bill_billamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billMonthly',
            field=models.BooleanField(default=False),
        ),
    ]
