# Generated by Django 4.1.7 on 2023-03-04 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_bill_billmonthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='userB',
        ),
        migrations.AddField(
            model_name='allowance',
            name='userMain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userMain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowance',
            name='userSub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userSub', to=settings.AUTH_USER_MODEL),
        ),
    ]
