# Generated by Django 4.1.7 on 2023-03-04 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_creditcarddetail_linked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddetail',
            name='linked_users',
            field=models.ManyToManyField(blank=True, related_name='linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
