# Generated by Django 4.1.6 on 2023-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
