# Generated by Django 4.1.7 on 2023-03-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
