# Generated by Django 4.1.6 on 2023-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_bill_billuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('statements', models.TextField(blank=True)),
            ],
        ),
    ]
